
version: "3"

services:


  backend:
    build: ./backend
    image: app
    ports:
      - "5000:8000"
    volumes:
      - ./backend:/code


  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080